### ISSUE TITLE
Planned macOS Support?

### ISSUE THREAD

**Issue by s0urfruit** [Lite3DP/Lite3DP-S1#1]
Hi there,

Is there any planned macOS support? 

I plan on backing the S1, but I can't seem to find a build guide for when I get my printer + a macOS version for converter, if not I may make one myself.

Thanks.

**Comment by eduo** [comment]
Subscribing to this. It seems the format is straightforward, but rather than a converted it would be nice to know the target files requirements, so a bash script can be made for Mac.

**Comment by Utopiah** [comment]
@s0urfruit definitely interested in the add-on board for control via WiFi. For now I keep an eye via a RPi Zero https://twitter.com/utopiah/status/1448388505139306502 but I'd like to keep track of the current status with a webpage or a rest API.

**Comment by lerouxb** [comment]
The TL;DR for using imagemagick to convert the png files you get in the zip from chitubox to the right bmp format is to put this in ~/.zshrc or ~/.bashrc and then you can run S1Convert where you extracted the zip:

```bash
function S1Convert() {
    mogrify -format PNG32 *.png
    mogrify -format bmp3 *.PNG32
    for f in *.bmp3; do mv -- "$f" "${f%.bmp3}.bmp"; done
    rm -f *.PNG32 *.png preview_cropping.* preview.* *.gcode
}
```

Copied from the discord here: https://discord.com/channels/902193261316288512/902202128322428928/909160122935291954

Thanks @s0urfruit !

**Comment by s0urfruit** [comment]
Just going to close it now.
